services:
  chatgpt-next-web:
    container_name: nextchat
    image: krccr.ccs.tencentyun.com/evanidea/next-chat:latest
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
